### ISSUE TITLE
Shape of entry data

### ISSUE THREAD

**Issue by ghost** [SmokinCaterpillar/doc2vec_user_comments#1]
Would it be possible to add a screenshot of how the entry- and processed data is structured. 
Particulary, the shape of :
`zeit_lists = load_files('./zeit2/')`
`spon_lists` = `load_files('./spon/')`
`fc_lists` = `load_files('./fc2/')`

as well as the shape of:
`articles`, `comments` and `tokens`.

The rest will be self explaining afterwards.
I am currently not able to rebuild any minimal working example and think this would help a lot to understand how the code works.
Thank you very much.

**Comment by SmokinCaterpillar** [comment]
Hey, I just replied to your mail. Anyhow, I suppose the data that is fed into `concate_dict` (yeah great typo^^) looks kinda like this:
`[([({'article_id':{'author':'xxx', 'body': 'yyy'}, ...}, {'comment_id':{'body': 'xxx', 'author': 'yyy'}}), ...], 'zeit'), ...]`
But let me check my old source code by Friday and get back to you.

**Comment by SmokinCaterpillar** [comment]
Hi, here are two of the downloads, just unzip it to get the required pickle files. I hope this helps.

[zeit_db.zip](https://github.com/SmokinCaterpillar/doc2vec_user_comments/files/3191062/zeit_db.zip)

**Comment by ghost** [comment]
Thank you so much Robert! This makes everything clear to me.
